import type { StaffMember } from "./schema"

export const initialStaff: StaffMember[] = [
  {
    id: "staff_1",
    firstName: "Marvin",
    lastName: "McKinney",
    email: "marvin@rackrage.com",
    phone: "9812345001",
    allowAdminAccess: false,
    dateOfBirth: "",
    gender: "",
    address: "",
    role: "Instructor",
    payType: "Per Class",
    payRate: 800,
    displayName: "Coach Marvin",
    instructorType: "Group Fitness Instructor",
    sports: "Yoga, Pilates",
    experience: "6 years",
    certifications: "Yoga Alliance 200hr",
    canBeBooked: true,
    visibility: "Public",
    maxConcurrentBookings: 1,
    activeInstructor: true,
    joined: "12 Jan 26",
    status: "Active",
  },
  {
    id: "staff_2",
    firstName: "Jerome",
    lastName: "Bell",
    email: "jerome@rackrage.com",
    phone: "9812345002",
    allowAdminAccess: false,
    dateOfBirth: "",
    gender: "",
    address: "",
    role: "Instructor",
    payType: "Hourly",
    payRate: 1200,
    displayName: "Jerome B.",
    instructorType: "Personal Trainer",
    sports: "Strength Training",
    experience: "8 years",
    certifications: "NASM-CPT",
    canBeBooked: true,
    visibility: "Public",
    maxConcurrentBookings: 1,
    activeInstructor: true,
    joined: "3 Feb 26",
    status: "Active",
  },
  {
    id: "staff_3",
    firstName: "Courtney",
    lastName: "Henry",
    email: "courtney@rackrage.com",
    phone: "9812345003",
    allowAdminAccess: true,
    dateOfBirth: "",
    gender: "",
    address: "",
    role: "Front Desk",
    payType: "Monthly",
    payRate: 35000,
    displayName: "",
    instructorType: "None",
    sports: "",
    experience: "",
    certifications: "",
    canBeBooked: false,
    visibility: "Public",
    maxConcurrentBookings: 1,
    activeInstructor: true,
    joined: "20 Feb 26",
    status: "Active",
  },
  {
    id: "staff_4",
    firstName: "Wade",
    lastName: "Warren",
    email: "wade@rackrage.com",
    phone: "9812345004",
    allowAdminAccess: false,
    dateOfBirth: "",
    gender: "",
    address: "",
    role: "Instructor",
    payType: "Per Class",
    payRate: 900,
    displayName: "Coach Wade",
    instructorType: "Boxing Coach",
    sports: "Boxing, CrossFit",
    experience: "5 years",
    certifications: "",
    canBeBooked: true,
    visibility: "Public",
    maxConcurrentBookings: 1,
    activeInstructor: true,
    joined: "5 Mar 26",
    status: "Active",
  },
  {
    id: "staff_5",
    firstName: "Devon",
    lastName: "Lane",
    email: "devon@rackrage.com",
    phone: "9812345005",
    allowAdminAccess: true,
    dateOfBirth: "",
    gender: "",
    address: "",
    role: "Manager",
    payType: "Monthly",
    payRate: 55000,
    displayName: "",
    instructorType: "None",
    sports: "",
    experience: "",
    certifications: "",
    canBeBooked: false,
    visibility: "Public",
    maxConcurrentBookings: 1,
    activeInstructor: true,
    joined: "1 Apr 26",
    status: "Active",
  },
  {
    id: "staff_6",
    firstName: "Cameron",
    lastName: "Williamson",
    email: "cameron@rackrage.com",
    phone: "9812345006",
    allowAdminAccess: false,
    dateOfBirth: "",
    gender: "",
    address: "",
    role: "Instructor",
    payType: "Hourly",
    payRate: 1100,
    displayName: "Cam W.",
    instructorType: "Personal Trainer",
    sports: "Boxing",
    experience: "4 years",
    certifications: "",
    canBeBooked: true,
    visibility: "Private",
    maxConcurrentBookings: 1,
    activeInstructor: false,
    joined: "18 Apr 26",
    status: "Inactive",
  },
]

export function generateStaffId() {
  return `staff_${Math.random().toString(36).slice(2, 10)}`
}
