import type { StaffMember } from "./schema"

export const initialStaff: StaffMember[] = [
  {
    id: "staff_1",
    firstName: "Marvin",
    lastName: "McKinney",
    email: "marvin@rackrage.com",
    phone: "9812345001",
    role: "Instructor",
    specialty: "Yoga & Pilates",
    payType: "Per Class",
    payRate: 800,
    joined: "12 Jan 26",
    status: "Active",
  },
  {
    id: "staff_2",
    firstName: "Jerome",
    lastName: "Bell",
    email: "jerome@rackrage.com",
    phone: "9812345002",
    role: "Personal Trainer",
    specialty: "Strength Training",
    payType: "Hourly",
    payRate: 1200,
    joined: "3 Feb 26",
    status: "Active",
  },
  {
    id: "staff_3",
    firstName: "Courtney",
    lastName: "Henry",
    email: "courtney@rackrage.com",
    phone: "9812345003",
    role: "Front Desk",
    specialty: "",
    payType: "Monthly",
    payRate: 35000,
    joined: "20 Feb 26",
    status: "Active",
  },
  {
    id: "staff_4",
    firstName: "Wade",
    lastName: "Warren",
    email: "wade@rackrage.com",
    phone: "9812345004",
    role: "Instructor",
    specialty: "CrossFit & HIIT",
    payType: "Per Class",
    payRate: 900,
    joined: "5 Mar 26",
    status: "Active",
  },
  {
    id: "staff_5",
    firstName: "Devon",
    lastName: "Lane",
    email: "devon@rackrage.com",
    phone: "9812345005",
    role: "Manager",
    specialty: "",
    payType: "Monthly",
    payRate: 55000,
    joined: "1 Apr 26",
    status: "Active",
  },
  {
    id: "staff_6",
    firstName: "Cameron",
    lastName: "Williamson",
    email: "cameron@rackrage.com",
    phone: "9812345006",
    role: "Personal Trainer",
    specialty: "Boxing",
    payType: "Hourly",
    payRate: 1100,
    joined: "18 Apr 26",
    status: "Inactive",
  },
]

export function generateStaffId() {
  return `staff_${Math.random().toString(36).slice(2, 10)}`
}
