export const areaAttributeOptions = [
  "Air Conditioned",
  "Heated",
  "Ventilated",
  "Mirrored Walls",
  "Sound System",
  "Bluetooth Audio",
  "Projector",
  "TV Screen",
  "Whiteboard",
  "Natural Light",
  "Blackout Blinds",
  "Sprung Floor",
  "Rubber Flooring",
  "Turf Flooring",
  "Carpeted",
  "Ground Floor",
  "Wheelchair Accessible",
  "Step-Free Access",
  "Lift Access",
  "Lockers Nearby",
  "Changing Room Nearby",
  "Showers Nearby",
  "Toilets Nearby",
  "Water Station",
  "Drinking Fountain",
  "Storage Space",
  "Equipment Storage",
  "First Aid Kit",
  "Defibrillator",
  "CCTV",
  "Security Access",
  "Keycard Entry",
  "WiFi",
  "Power Outlets",
  "Charging Points",
  "Seating Area",
  "Spectator Area",
  "Reception Nearby",
  "Parking Nearby",
  "Bike Racks",
  "Wheelchair Parking",
  "Outdoor",
  "Covered Outdoor",
  "Shaded",
  "Floodlit",
  "Climate Controlled",
  "Soundproofed",
  "Private Entrance",
  "Pet Friendly",
  "Kids Friendly",
] as const
