export const areaAttributeOptions = [
  "Air Conditioned",
  "Mirrored Walls",
  "Sound System",
  "TV Screen",
  "Natural Light",
  "Ground Floor",
  "Wheelchair Accessible",
  "Lockers Nearby",
  "Showers Nearby",
  "Water Station",
  "WiFi",
  "CCTV",
  "Parking Nearby",
  "Outdoor",
  "Kids Friendly",
] as const
