import type { Member } from "./schema"

export const initialMembers: Member[] = [
  {
    id: "mem_1",
    firstName: "Savannah",
    lastName: "Nguyen",
    email: "savannah@234.com",
    phone: "9812340001",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_3", planName: "Annual Elite" }],
    joined: "1 Feb 26",
    status: "Active",
  },
  {
    id: "mem_2",
    firstName: "Kathryn",
    lastName: "Murphy",
    email: "kathryn@114.com",
    phone: "9812340002",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_2", planName: "Silver Membership" }],
    joined: "2 Feb 26",
    status: "On Hold",
  },
  {
    id: "mem_3",
    firstName: "Courtney",
    lastName: "Henry",
    email: "henry@courtney.com",
    phone: "9812340003",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_5", planName: "Family Pack" }],
    joined: "15 Feb 26",
    status: "Active",
  },
  {
    id: "mem_4",
    firstName: "Kristin",
    lastName: "Watson",
    email: "kristin@gmail.com",
    phone: "9812340004",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_1", planName: "Gold Membership" }],
    joined: "15 Feb 26",
    status: "Active",
  },
  {
    id: "mem_5",
    firstName: "Theresa",
    lastName: "Webb",
    email: "webb@gmail.com",
    phone: "9812340005",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_2", planName: "Silver Membership" }],
    joined: "23 Feb 26",
    status: "Expired",
  },
  {
    id: "mem_6",
    firstName: "Brooklyn",
    lastName: "Simmons",
    email: "brooklyn@moms.com",
    phone: "9812340006",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_3", planName: "Annual Elite" }],
    joined: "25 Feb 26",
    status: "Active",
  },
  {
    id: "mem_7",
    firstName: "Ralph",
    lastName: "Edwards",
    email: "ralph@edwards.com",
    phone: "9812340007",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [],
    joined: "25 Feb 26",
    status: "Expired",
  },
  {
    id: "mem_8",
    firstName: "Wade",
    lastName: "Warren",
    email: "naguyen@warren.com",
    phone: "9812340008",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_2", planName: "Silver Membership" }],
    joined: "16 Mar 26",
    status: "On Hold",
  },
  {
    id: "mem_9",
    firstName: "Eleanor",
    lastName: "Pena",
    email: "eleanor@warren.com",
    phone: "9812340009",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_3", planName: "Annual Elite" }],
    joined: "16 Mar 26",
    status: "Active",
  },
  {
    id: "mem_10",
    firstName: "Marvin",
    lastName: "McKinney",
    email: "marvin@warren.com",
    phone: "9812340010",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [{ planId: "plan_2", planName: "Silver Membership" }],
    joined: "20 Mar 26",
    status: "Active",
  },
  {
    id: "mem_11",
    firstName: "Ronald",
    lastName: "Richards",
    email: "ronald@warren.com",
    phone: "9812340011",
    dateOfBirth: "",
    gender: "",
    address: "",
    memberships: [],
    joined: "20 Mar 26",
    status: "Expired",
  },
]
