import type { Product } from "./schema"

export const initialProducts: Product[] = [
  {
    id: "prod_1",
    name: "Whey Protein 1kg",
    category: "Supplements",
    brand: "Optimum Nutrition",
    barcode: "",
    sku: "WP-1KG",
    visibility: "Public",
    active: true,
    price: 3499,
    costPrice: 2400,
    revenueAccount: "Supplement Sales",
    taxRate: "13%",
    description: "",
    features: "Best Seller",
  },
  {
    id: "prod_2",
    name: "Creatine Monohydrate 500g",
    category: "Supplements",
    brand: "MyProtein",
    barcode: "",
    sku: "CM-500",
    visibility: "Public",
    active: true,
    price: 1999,
    costPrice: 1200,
    revenueAccount: "Supplement Sales",
    taxRate: "13%",
    description: "",
    features: "",
  },
  {
    id: "prod_3",
    name: "Gym Tank Top",
    category: "Apparel",
    brand: "Gymshark",
    barcode: "",
    sku: "GTT-BLK",
    visibility: "Public",
    active: true,
    price: 2200,
    costPrice: 900,
    revenueAccount: "Apparel Sales",
    taxRate: "13%",
    description: "",
    features: "New Arrival",
  },
  {
    id: "prod_4",
    name: "Lifting Straps",
    category: "Accessories",
    brand: "Generic",
    barcode: "",
    sku: "LS-01",
    visibility: "Public",
    active: true,
    price: 1450,
    costPrice: 600,
    revenueAccount: "Retail Revenue",
    taxRate: "13%",
    description: "",
    features: "",
  },
  {
    id: "prod_5",
    name: "Adjustable Dumbbell Set",
    category: "Equipment",
    brand: "Generic",
    barcode: "",
    sku: "ADS-20",
    visibility: "Public",
    active: true,
    price: 18900,
    costPrice: 14000,
    revenueAccount: "Retail Revenue",
    taxRate: "13%",
    description: "",
    features: "",
  },
  {
    id: "prod_6",
    name: "Shaker Bottle",
    category: "Accessories",
    brand: "Generic",
    barcode: "",
    sku: "SB-700",
    visibility: "Private",
    active: false,
    price: 999,
    costPrice: 400,
    revenueAccount: "Retail Revenue",
    taxRate: "13%",
    description: "",
    features: "",
  },
]
