import type { Plan } from "./schema"

export const initialPlans: Plan[] = [
  {
    id: "plan_1",
    name: "Gold Membership",
    category: "Individual",
    barcode: "",
    visibility: "Public",
    description: "Full access to all classes, equipment, and locker rooms.",
    active: true,
    pricePerPeriod: 7900,
    billingType: "Monthly",
    signupFee: 1000,
    requirePaymentUpfront: true,
    coverage: "Full facility access",
    sessions: "",
    features: "Personal Training",
    sports: "",
    members: 112,
  },
  {
    id: "plan_2",
    name: "Silver Membership",
    category: "Individual",
    barcode: "",
    visibility: "Public",
    description: "Access to gym floor and open classes.",
    active: true,
    pricePerPeriod: 4900,
    billingType: "Monthly",
    signupFee: 0,
    requirePaymentUpfront: true,
    coverage: "General plan",
    sessions: "",
    features: "Group Classes",
    sports: "",
    members: 86,
  },
  {
    id: "plan_3",
    name: "Annual Elite",
    category: "Individual",
    barcode: "",
    visibility: "Public",
    description: "Best value plan with personal training sessions included.",
    active: true,
    pricePerPeriod: 72000,
    billingType: "Annual",
    signupFee: 0,
    requirePaymentUpfront: true,
    coverage: "Full facility access",
    sessions: "",
    features: "Personal Training",
    sports: "",
    members: 34,
  },
  {
    id: "plan_4",
    name: "Student Quarterly",
    category: "Student",
    barcode: "",
    visibility: "Public",
    description: "Discounted plan for verified students.",
    active: false,
    pricePerPeriod: 9900,
    billingType: "Quarterly",
    signupFee: 0,
    requirePaymentUpfront: true,
    coverage: "General plan",
    sessions: "",
    features: "",
    sports: "",
    members: 0,
  },
  {
    id: "plan_5",
    name: "Family Pack",
    category: "Family",
    barcode: "",
    visibility: "Private",
    description: "Shared plan for up to 4 family members.",
    active: true,
    pricePerPeriod: 15900,
    billingType: "Monthly",
    signupFee: 1500,
    requirePaymentUpfront: false,
    coverage: "Full facility access",
    sessions: "",
    features: "Locker",
    sports: "",
    members: 16,
  },
]
